-- Exercício 01:
USE hr;
SHOW COLUMNS FROM locations;
ALTER TABLE locations CHANGE STREET_ADDRESS ADDRESS VARCHAR(40);
SHOW COLUMNS FROM locations;
--

-- Exercício 02:
USE hr;
SHOW COLUMNS FROM regions;
ALTER TABLE regions CHANGE REGION_NAME REGION VARCHAR(25);
SHOW COLUMNS FROM regions;
-- 

-- Exercício 03:
USE hr;
SHOW COLUMNS FROM countries;
ALTER TABLE countries CHANGE COUNTRY_NAME COUNTRY VARCHAR(40);
SHOW COLUMNS FROM countries;
-- 